# Generated by Django 4.1.4 on 2023-04-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
