# Generated by Django 4.1.4 on 2023-04-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='owner',
        ),
    ]
